version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: logistica_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: logistica
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: logistica_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: